### ISSUE TITLE
Document: Drag And Drop Upload

### ISSUE THREAD

**Issue by vi117** [vi117/scrap-yard#8]
액터: 사용자  
시작조건: 문서 수정 권한이 있어야 한다.  
목표: 업로드를 드래그 앤 드롭으로 한다.

1. 웹사이트의 그림이나 비디오 등의 파일을 Drag And Drop 해서 Chunk 사이에 놓으면 시작된다.
2. Drag And Drop된 파일을 서버에 업로드한다. 업로드시 파일 이름이 중복될 때 파일 이름이 밑줄과 숫자로 끝나지 않으면 이름의 뒤에 "_1"을 붙여 업로드 한다. 숫자로 끝나면 다음 숫자를 붙여서 업로드 한다. 파일 이름이 없다면 임의의 이름을 붙여서 업로드 한다.
3. 그 파일을 새로운 Chunk로 추가한다. 이때 웹에서 표시가능한 파일(이미지, 동영상)이면 파일을 표시하는 Chunk를 추가하고 아니면 다운로드 링크를 가진 Chunk를 추가한다.

대체흐름:

A. 파일 사이즈 큼
   1. 기본단계 2에서 파일 사이즈가 설정보다 크면 시작한다.
   2. 파일 크기가 너무 크다는 메세지로 띄우고 종료한다.

B. 작은 파일 사이즈
   1. 기본단계 2에서 파일 사이즈가 설정보다 작으면 시작한다.
   2. 파일을 base64로 인코딩해서 Chunk로 삽입한다.

```mermaid
flowchart LR
    Start((start)) -->|on drop| upload([upload])
    upload --> tryupload{try upload}
    tryupload -->|file too big| cancel([upload fail])
    tryupload -->|on success| complete([complete])
    tryupload -->|file small| inlining([inlining content])
```

**Comment by teyalem** [comment]
#56 에 포함됨.
